services:
  - type: web
    name: awetu-clinic-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: CHAPA_SECRET_KEY
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: TEXTBEE_API_KEY
        sync: false
      - key: TEXTBEE_DEVICE_ID
        sync: false
